### ISSUE TITLE
Glitched wild battle after losing to a trainer

### ISSUE THREAD

**Issue by mattymannnn** [jiangzhengwenjz/Double_wild_battle#1]
If you lose to a trainer that has at least 1 more Pokemon left after the Pokemon you lost to, then the next single wild battle you encounter will be glitched. If you defeat the single wild Pokemon, another Pokemon will be sent out as if it was a trainer battle. The second Pokemon sent out will be from the trainer you had previously lost to.

**Comment by jiangzhengwenjz** [comment]
Late reply but this repo is no longer in dev.
